"use client";

import { useEffect, useRef, useMemo, useDeferredValue, useState } from "react";
import L from "leaflet";

// Load computed data if available, otherwise mock
let venueModule: any;
try {
  venueModule = require("../data/venues-computed");
} catch {
  venueModule = require("../data/mock-venues");
}

let unconfirmedModule: { unconfirmedVenues: any[] } | null = null;
try {
  unconfirmedModule = require("../data/venues-unconfirmed");
} catch {
  // venues-unconfirmed.ts doesn't exist yet
}

import { type WeatherData, getSymbolInfo } from "../lib/weather";
import { METRO_STATIONS, type MetroStation, STATION_RADIUS_M, distanceM } from "../data/metro-stations";
import { getFavorites, toggleFavorite } from "../lib/favorites";

// Optional metro network data (tracks + stations + entrances) — generated by pipeline/09_fetch_metro.py
let metroNetwork: {
  METRO_TRACKS: { color: "red" | "green" | "blue"; coords: [number, number][] }[];
  METRO_STATIONS: { lat: number; lng: number; name: string }[];
  METRO_ENTRANCES: { lat: number; lng: number; name: string; link: [[number, number], [number, number]] }[];
} | null = null;

/**
 * Chaikin corner-cutting — 3 iterations ger mjuka bezier-liknande kurvor.
 * Bevarar exakta start/slut-koordinater så angränsande ways fortfarande
 * möts utan glapp.
 */
function chaikin(pts: [number, number][], iterations = 3): [number, number][] {
  if (pts.length < 3) return pts;
  let cur = pts;
  for (let iter = 0; iter < iterations; iter++) {
    const out: [number, number][] = [cur[0]];
    for (let i = 0; i < cur.length - 1; i++) {
      const [lat1, lng1] = cur[i];
      const [lat2, lng2] = cur[i + 1];
      out.push([lat1 + 0.25 * (lat2 - lat1), lng1 + 0.25 * (lng2 - lng1)]);
      out.push([lat1 + 0.75 * (lat2 - lat1), lng1 + 0.75 * (lng2 - lng1)]);
    }
    out.push(cur[cur.length - 1]);
    cur = out;
  }
  return cur;
}

/** Closest point on segment [p1,p2] to (lat,lng). */
function nearestOnSegment(
  lat: number, lng: number,
  [lat1, lng1]: [number, number],
  [lat2, lng2]: [number, number],
): [number, number] {
  const dx = lat2 - lat1, dy = lng2 - lng1;
  const lenSq = dx * dx + dy * dy;
  if (lenSq === 0) return [lat1, lng1];
  const t = Math.max(0, Math.min(1, ((lat - lat1) * dx + (lng - lng1) * dy) / lenSq));
  return [lat1 + t * dx, lng1 + t * dy];
}

type SnapResult = {
  pos: [number, number];
  color: "red" | "green" | "blue";
  dir: [number, number];
  trackIdx: number;
  segIdx: number;
  // Filled in after neighbor-direction pass and interpAtDist:
  pa?: [number, number];
  pb?: [number, number];
  platDir?: [number, number];
};

/** Snap (lat,lng) to nearest point on pre-smoothed tracks. Returns position, color,
 *  local tangent direction, plus which track and segment index for neighbor computation. */
function snapToTrack(
  lat: number,
  lng: number,
  tracks: { color: "red" | "green" | "blue"; coords: [number, number][] }[],
): SnapResult {
  let bestDist = Infinity;
  let bestPos: [number, number] = [lat, lng];
  let bestColor: "red" | "green" | "blue" = "red";
  let bestDir: [number, number] = [1, 0];
  let bestTrackIdx = 0, bestSegIdx = 0;
  const cosLat = Math.cos((lat * Math.PI) / 180);

  for (let ti = 0; ti < tracks.length; ti++) {
    const c = tracks[ti].coords as [number, number][];
    for (let i = 0; i < c.length - 1; i++) {
      const pt = nearestOnSegment(lat, lng, c[i], c[i + 1]);
      const dlat = pt[0] - lat, dlng = (pt[1] - lng) * cosLat;
      const d2 = dlat * dlat + dlng * dlng;
      if (d2 < bestDist) {
        bestDist = d2; bestPos = pt; bestColor = tracks[ti].color;
        bestTrackIdx = ti; bestSegIdx = i;
        const sdLat = c[i + 1][0] - c[i][0], sdLng = c[i + 1][1] - c[i][1];
        const norm = Math.hypot(sdLat, sdLng * cosLat) || 1;
        bestDir = [sdLat / norm, sdLng / norm];
      }
    }
  }
  return { pos: bestPos, color: bestColor, dir: bestDir, trackIdx: bestTrackIdx, segIdx: bestSegIdx };
}

/**
 * Förskjut ett spår lateralt (normalt mot spårriktningen) med offsetM meter.
 * Positiv = höger sett i spårets riktning. Används för att separera parallella linjer.
 */
/**
 * Förskjut ett spår lateralt offsetM meter (positiv = höger sett i spårets riktning).
 *
 * Tangenten beräknas med ett glidande medelvärde (windowSize punkter) för att
 * undvika "darriga" parallella linjer när GTFS-datan har mikro-hack.
 * Normalen roteras 90° medurs i skärmrymden (Mercator-korrigerat).
 */
function applyLateralOffset(
  coords: [number, number][],
  offsetM: number,
  windowSize = 11,
): [number, number][] {
  if (Math.abs(offsetM) < 0.1 || coords.length < 2) return coords;
  const half = Math.floor(windowSize / 2);
  return coords.map((pt, i) => {
    const cosLat = Math.cos(pt[0] * Math.PI / 180);
    // Glidande medelvärde: tangent från [lo, hi] istället för enstaka grannpar
    const lo = Math.max(0, i - half);
    const hi = Math.min(coords.length - 1, i + half);
    const dlat = coords[hi][0] - coords[lo][0];
    const dlng = coords[hi][1] - coords[lo][1];
    const lenM = Math.hypot(dlat * 111_000, dlng * 111_000 * cosLat) || 1;
    const dLatDeg = -dlng * cosLat * offsetM / lenM;
    const dLngDeg =  dlat * offsetM / (lenM * cosLat);
    return [pt[0] + dLatDeg, pt[1] + dLngDeg] as [number, number];
  });
}

/** Approximate distance (m) from a point to any coord on the track (sampled). */
function approxDistToTrack(
  lat: number, lng: number,
  coords: [number, number][],
  cosLat: number,
): number {
  let best = Infinity;
  const step = Math.max(1, Math.floor(coords.length / 120));
  for (let i = 0; i < coords.length; i += step) {
    const d = Math.hypot((coords[i][0] - lat) * 111_000, (coords[i][1] - lng) * 111_000 * cosLat);
    if (d < best) best = d;
  }
  return best;
}

/** Build cumulative distance array (meters) for every point along a track. */
function buildCumDist(coords: [number, number][], cosLat: number): Float64Array {
  const d = new Float64Array(coords.length);
  for (let i = 1; i < coords.length; i++) {
    const dlat = (coords[i][0] - coords[i - 1][0]) * 111_000;
    const dlng = (coords[i][1] - coords[i - 1][1]) * 111_000 * cosLat;
    d[i] = d[i - 1] + Math.hypot(dlat, dlng);
  }
  return d;
}

/** Linearly interpolate exact [lat, lng] at distance d along the track. */
function interpAtDist(
  coords: [number, number][],
  cumDist: Float64Array,
  d: number,
): [number, number] {
  if (d <= 0) return coords[0];
  const last = cumDist.length - 1;
  if (d >= cumDist[last]) return coords[last];
  let lo = 0, hi = last;
  while (lo < hi - 1) { const mid = (lo + hi) >> 1; if (cumDist[mid] <= d) lo = mid; else hi = mid; }
  const t = (cumDist[lo + 1] - cumDist[lo]) > 0 ? (d - cumDist[lo]) / (cumDist[lo + 1] - cumDist[lo]) : 0;
  return [
    coords[lo][0] + t * (coords[lo + 1][0] - coords[lo][0]),
    coords[lo][1] + t * (coords[lo + 1][1] - coords[lo][1]),
  ];
}

/**
 * Distance-Based Reconstruction — bygger ett NYTT spår utan att modifiera det gamla.
 *
 * 1. Beräknar kumulativt avstånd (meter) för varje punkt.
 * 2. Hittar stationens avstånd D längs spåret (aldrig index-baserat).
 * 3. Definierar perrong-zonen [D-halfM, D+halfM].
 * 4. Bygger ny array: punkter < D-halfM | exakt pa vid D-halfM | exakt pb vid D+halfM | punkter > D+halfM.
 * Ingen punkt existerar inuti zonen → spåret kan aldrig backa eller loopa.
 */
function platformizeTrack(
  rawCoords: [number, number][],
  stations: { pos: [number, number]; dir: [number, number] }[],
  halfM: number,
): [number, number][] {
  if (stations.length === 0 || rawCoords.length < 4) return rawCoords;

  const midLat = rawCoords[Math.floor(rawCoords.length / 2)][0];
  const cosLat = Math.cos((midLat * Math.PI) / 180);
  const cumDist = buildCumDist(rawCoords, cosLat);
  const totalLen = cumDist[cumDist.length - 1];

  type Interval = { dStart: number; dEnd: number; pa: [number, number]; pb: [number, number] };
  const intervals: Interval[] = [];

  for (const s of stations) {
    // Hitta närmaste punkt i dessa koordinater (grov → fin)
    const step = Math.max(1, Math.floor(rawCoords.length / 200));
    let bestD2 = Infinity, bestIdx = 0;
    for (let i = 0; i < rawCoords.length; i += step) {
      const dlat = rawCoords[i][0] - s.pos[0], dlng = (rawCoords[i][1] - s.pos[1]) * cosLat;
      const d2 = dlat * dlat + dlng * dlng;
      if (d2 < bestD2) { bestD2 = d2; bestIdx = i; }
    }
    const rlo = Math.max(0, bestIdx - step), rhi = Math.min(rawCoords.length - 1, bestIdx + step);
    for (let i = rlo; i <= rhi; i++) {
      const dlat = rawCoords[i][0] - s.pos[0], dlng = (rawCoords[i][1] - s.pos[1]) * cosLat;
      const d2 = dlat * dlat + dlng * dlng;
      if (d2 < bestD2) { bestD2 = d2; bestIdx = i; }
    }

    const stDist = cumDist[bestIdx];
    const dStart = Math.max(0, stDist - halfM);
    const dEnd   = Math.min(totalLen, stDist + halfM);

    // Interpolera exakta positioner på spåret (inte offset från neighbor-riktning)
    intervals.push({
      dStart, dEnd,
      pa: interpAtDist(rawCoords, cumDist, dStart),
      pb: interpAtDist(rawCoords, cumDist, dEnd),
    });
  }

  intervals.sort((a, b) => a.dStart - b.dStart);

  // Enpasbygge — rör oss framåt längs spåret, hoppar aldrig bakåt
  const result: [number, number][] = [];
  let m = 0, injected = false;

  for (let i = 0; i < rawCoords.length; i++) {
    const d = cumDist[i];

    // Avancera förbi fullständigt passerade intervall
    while (m < intervals.length && d > intervals[m].dEnd) { m++; injected = false; }

    if (m >= intervals.length || d < intervals[m].dStart) {
      result.push(rawCoords[i]); // utanför alla zoner — behåll
    } else {
      if (!injected) {
        result.push(intervals[m].pa); // exakt D-halfM
        result.push(intervals[m].pb); // exakt D+halfM
        injected = true;
      }
      // Inuti dead zone — hoppa över originalkoordinaten
    }
  }

  return result;
}

/** Offset a map position by dist_m along a normalized direction vector. */
function offsetAlongDir(
  center: [number, number],
  dir: [number, number],
  dist_m: number,
): [number, number] {
  const cosLat = Math.cos((center[0] * Math.PI) / 180);
  return [
    center[0] + (dir[0] * dist_m) / 111_000,
    center[1] + (dir[1] * dist_m) / (111_000 * cosLat),
  ];
}
try {
  metroNetwork = require("../data/metro-network");
} catch {
  // metro-network.ts doesn't exist yet
}

export interface FeedbackVenue {
  id: string;
  name: string;
  type: string;
  currentSchedule: Record<number, "sun" | "shade" | "night">;
  mode?: "schedule" | "seating";
}

export const VENUE_TYPES = ["restaurant", "cafe", "bar", "rooftop"] as const;
export type VenueType = (typeof VENUE_TYPES)[number];

/** Check if a venue passes the typeFilter. "bar" matches bar+pub, "rooftop" uses pipeline-computed flag. */
function matchesTypeFilter(venue: { type: string; rooftop?: boolean }, typeFilter: Set<VenueType>): boolean {
  if (typeFilter.size === 0) return true;
  if (typeFilter.has("restaurant") && venue.type === "restaurant") return true;
  if (typeFilter.has("cafe") && venue.type === "cafe") return true;
  if (typeFilter.has("bar") && (venue.type === "bar" || venue.type === "pub")) return true;
  if (typeFilter.has("rooftop") && venue.rooftop) return true;
  return false;
}

export type SunRange = { from: number; to: number } | null;

interface SunMapProps {
  hour: number;
  date: Date;
  filter: "all" | "sun" | "shade";
  typeFilter: Set<VenueType>;
  sunRange: SunRange;
  weather: WeatherData | null;
  onFeedback?: (venue: FeedbackVenue) => void;
  showShadows?: boolean;
  showMetro?: boolean;
  focusVenueId?: string | null;
  onFocusHandled?: () => void;
  metroStation?: MetroStation | null;
}

type NormalizedStatus = "sun" | "shade" | "partial" | "night";

/** Normalize status from both formats: mock ("sun"/"shade") and computed ("s"/"d") */
function normalize(status: string): NormalizedStatus {
  switch (status) {
    case "sun": case "s": return "sun";
    case "shade": case "d": return "shade";
    case "partial": case "p": return "partial";
    case "night": case "n": return "night";
    default: return "shade";
  }
}

function statusToLabel(s: NormalizedStatus): string {
  return { sun: "Sol", partial: "Delvis sol", shade: "Skugga", night: "Natt" }[s];
}

function statusToEmoji(s: NormalizedStatus): string {
  return { sun: "\u2600\uFE0F", partial: "\u26C5", shade: "\uD83C\uDF25\uFE0F", night: "\uD83C\uDF19" }[s];
}

function typeToLabel(type: string): string {
  return { restaurant: "Restaurang", cafe: "Café", bar: "Bar", pub: "Pub" }[type] ?? type;
}

function typeToSvgIcon(type: string): string {
  const icons: Record<string, string> = {
    restaurant: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#555" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3zm0 0v7"/></svg>`,
    cafe: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#555" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M17 8h1a4 4 0 1 1 0 8h-1"/><path d="M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4Z"/><line x1="6" y1="2" x2="6" y2="4"/><line x1="10" y1="2" x2="10" y2="4"/><line x1="14" y1="2" x2="14" y2="4"/></svg>`,
    bar: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#555" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M8 22h8"/><path d="M12 11v11"/><path d="m19 3-7 8-7-8Z"/></svg>`,
    pub: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#555" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M8 22h8"/><path d="M12 11v11"/><path d="m19 3-7 8-7-8Z"/></svg>`,
  };
  return icons[type] ?? "";
}

function getSunPeriod(venue: any, dateKey: string): string {
  const hours = Array.from({ length: 16 }, (_, i) => i + 7);
  let first = -1;
  let last = -1;
  for (const h of hours) {
    const s = normalize(getStatus(venue, dateKey, h));
    if (s === "sun") {
      if (first === -1) first = h;
      last = h;
    }
  }
  if (first === -1) return "Ingen sol";
  if (first === last) return `Sol kl ${first}`;
  return `Sol ${first}–${last}`;
}

/** Find the best hour today: sun + best weather. Returns { hour, label } or null. */
function getBestHour(venue: any, dateKey: string, weather: WeatherData | null): { hour: number; label: string } | null {
  const hours = Array.from({ length: 16 }, (_, i) => i + 7);
  let bestHour = -1;
  let bestScore = -1;

  for (const h of hours) {
    const s = normalize(getStatus(venue, dateKey, h));
    if (s !== "sun") continue;

    // Score: sun = base 10, weather bonus
    let score = 10;
    if (weather?.hourly[h]) {
      const sym = weather.hourly[h].symbolCode;
      if (sym <= 2) score += 5;       // clear sky
      else if (sym <= 4) score += 2;  // partly cloudy
      else if (sym >= 8) score -= 10; // rain/thunder — disqualify

      // Prefer comfortable temps (18-24)
      const temp = weather.hourly[h].temperature;
      if (temp >= 18 && temp <= 24) score += 3;
      else if (temp >= 15 && temp <= 27) score += 1;

      // Penalize strong wind
      if (weather.hourly[h].windSpeed > 8) score -= 2;
    }

    if (score > bestScore) {
      bestScore = score;
      bestHour = h;
    }
  }

  if (bestHour === -1) return null;

  const w = weather?.hourly[bestHour];
  let label = `Kl ${bestHour}:00`;
  if (w) {
    const sym = getSymbolInfo(w.symbolCode);
    label += ` — ${sym.icon} ${Math.round(w.temperature)}\u00b0C`;
  }
  return { hour: bestHour, label };
}

const getDateKey = venueModule.getClosestDateKey;
const getStatus = venueModule.getVenueStatus ?? venueModule.getVenueStatus;
const getSunHrs = venueModule.getSunHours;
const allVenues = venueModule.venues ?? venueModule.mockVenues;

// Badge collision detection — estimate badge bounding boxes in pixel space
// and reassign positions (above/right/left/below) to minimize overlap
const BADGE_W = 130;
const BADGE_H = 32;
const POSITIONS = ["badge-above", "badge-right", "badge-left", "badge-below"] as const;

function resolveBadgeCollisions(map: L.Map, markers: L.Marker[]) {
  if (map.getZoom() < 17) return;

  interface Rect { x: number; y: number; w: number; h: number; idx: number; pos: number; }

  function getRect(px: L.Point, pos: number): Omit<Rect, "idx"> {
    const w = BADGE_W, h = BADGE_H;
    switch (pos) {
      case 0: return { x: px.x - w / 2, y: px.y - h - 12, w, h, pos }; // above
      case 1: return { x: px.x + 14, y: px.y - h / 2, w, h, pos };     // right
      case 2: return { x: px.x - w - 14, y: px.y - h / 2, w, h, pos }; // left
      case 3: return { x: px.x - w / 2, y: px.y + 14, w, h, pos };     // below
      default: return { x: px.x - w / 2, y: px.y - h - 12, w, h, pos };
    }
  }

  function overlaps(a: Omit<Rect, "idx">, b: Omit<Rect, "idx">): boolean {
    return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
  }

  // Get pixel positions for all markers. Skip ones currently hidden by the
  // sun/shade filter (display:none) so they don't reserve collision slots.
  const items: { px: L.Point; el: HTMLElement }[] = [];
  for (const m of markers) {
    const iconEl = (m as any)._icon as HTMLElement | undefined;
    if (!iconEl || iconEl.style.display === "none") continue;
    const el = iconEl.querySelector(".marker-badge") as HTMLElement | null;
    if (!el) continue;
    const px = map.latLngToContainerPoint(m.getLatLng());
    items.push({ px, el });
  }

  // Greedily assign positions, preferring above, then right, left, below
  const placed: Omit<Rect, "idx">[] = [];
  for (const item of items) {
    let best = 0;
    for (let p = 0; p < 4; p++) {
      const rect = getRect(item.px, p);
      const hasCollision = placed.some((r) => overlaps(rect, r));
      if (!hasCollision) { best = p; break; }
      if (p === 0) best = p; // fallback to above if all collide
    }
    const finalRect = getRect(item.px, best);
    placed.push(finalRect);

    // Apply position class
    for (const cls of POSITIONS) item.el.classList.remove(cls);
    item.el.classList.add(POSITIONS[best]);
  }
}

/**
 * Sunrise/sunset in local CEST hours for Stockholm (59.33°N, 18.07°E).
 * Uses a standard solar declination approximation — accurate to within ~5 min
 * for our purposes, which is plenty for an ambient lighting effect.
 */
function getSunTimes(date: Date): { sunrise: number; sunset: number } {
  const lat = 59.33;
  const lng = 18.07;
  const start = new Date(date.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((date.getTime() - start.getTime()) / 86400000);
  const decl = 0.4093 * Math.sin((2 * Math.PI * (dayOfYear - 81)) / 365);
  const cosH = -Math.tan((lat * Math.PI) / 180) * Math.tan(decl);
  if (cosH >= 1) return { sunrise: 12, sunset: 12 };   // polar night (not expected Apr–Oct)
  if (cosH <= -1) return { sunrise: 0, sunset: 24 };   // midnight sun
  const H = (Math.acos(cosH) * 180) / Math.PI;
  const hours = H / 15;
  const solarNoon = 12 - lng / 15 + 2; // CEST (UTC+2), matches shadow pipeline
  return { sunrise: solarNoon - hours, sunset: solarNoon + hours };
}

/**
 * Calculate ambient darkness (0 = bright daylight, 1 = dark night).
 * Follows the actual sunrise/sunset for the selected date, and adds extra
 * darkening for overcast/rainy weather.
 */
function getAmbientDarkness(hour: number, date: Date, weatherSymbol?: number): number {
  const { sunrise, sunset } = getSunTimes(date);

  // Twilight curve anchored to sunrise/sunset.
  //   Deep night until 1.5h before sunrise, dawn ramp down to full daylight ~1h after,
  //   then full daylight until 1h before sunset, golden-hour ramp up to deep night ~1.5h after.
  let timeDark: number;
  if (hour <= sunrise - 1.5) timeDark = 0.55;
  else if (hour <= sunrise - 0.25) timeDark = 0.55 - ((hour - (sunrise - 1.5)) / 1.25) * 0.35;
  else if (hour <= sunrise + 1) timeDark = 0.20 - ((hour - (sunrise - 0.25)) / 1.25) * 0.20;
  else if (hour <= sunset - 1) timeDark = 0;
  else if (hour <= sunset + 0.25) timeDark = ((hour - (sunset - 1)) / 1.25) * 0.20;
  else if (hour <= sunset + 1.5) timeDark = 0.20 + ((hour - (sunset + 0.25)) / 1.25) * 0.35;
  else timeDark = 0.55;

  // Weather-based adjustment. Clear sky adds a tiny warm overlay (tinted below),
  // while overcast/rain/thunder layers on substantial darkness.
  let weatherDark = 0;
  if (weatherSymbol !== undefined) {
    if (weatherSymbol === 1) weatherDark = 0.03;
    else if (weatherSymbol === 2) weatherDark = 0.02;
    else if (weatherSymbol === 3) weatherDark = 0.05;
    else if (weatherSymbol === 4) weatherDark = 0.11;
    else if (weatherSymbol === 5) weatherDark = 0.18;
    else if (weatherSymbol === 6) weatherDark = 0.26;
    else if (weatherSymbol === 7) weatherDark = 0.20;
    else if (weatherSymbol >= 8 && weatherSymbol <= 10) weatherDark = 0.20 + (weatherSymbol - 8) * 0.05;
    else if (weatherSymbol === 11 || weatherSymbol === 21) weatherDark = 0.34;
    else if (weatherSymbol >= 12 && weatherSymbol <= 17) weatherDark = 0.20;
    else if (weatherSymbol >= 18 && weatherSymbol <= 20) weatherDark = 0.24 + (weatherSymbol - 18) * 0.05;
    else if (weatherSymbol >= 22 && weatherSymbol <= 24) weatherDark = 0.22;
    else if (weatherSymbol >= 25 && weatherSymbol <= 27) weatherDark = 0.26;
  }

  return Math.max(0, Math.min(timeDark + weatherDark, 0.65));
}

/** Get warm/cool tint color based on time of day and weather */
function getAmbientColor(hour: number, date: Date, weatherSymbol?: number): string {
  const { sunrise, sunset } = getSunTimes(date);

  // Rain/thunder — deep cold grey-blue
  if (
    weatherSymbol &&
    (weatherSymbol === 11 ||
      weatherSymbol === 21 ||
      (weatherSymbol >= 8 && weatherSymbol <= 10) ||
      (weatherSymbol >= 18 && weatherSymbol <= 20))
  ) {
    return "35, 42, 58";
  }

  // Overcast / fog — flat grey
  if (weatherSymbol === 5 || weatherSymbol === 6 || weatherSymbol === 7) {
    return "60, 65, 78";
  }

  // Clear / nearly clear during daytime — warm golden overlay so slight alpha reads as sunlit
  if (weatherSymbol !== undefined && weatherSymbol <= 2 && hour > sunrise && hour < sunset) {
    return "255, 210, 140";
  }

  // Golden hour around sunset — warm orange
  if (hour >= sunset - 0.5 && hour <= sunset + 1) return "60, 30, 15";

  // Pre-dawn / late evening — cool blue-purple
  if (hour <= sunrise + 0.5 || hour >= sunset + 1) return "30, 25, 55";

  return "15, 23, 42"; // neutral slate
}

// Cache for loaded shadow GeoJSON
const shadowCache = new Map<string, any>();

// Per-venue caches for the photo + hours endpoints. Lazy popup HTML rebuilds
// the popup DOM on every open, which would otherwise re-fetch both endpoints
// each time the user reopens a popup (the previous version relied on a
// `dataset.loaded` flag on a persistent DOM node). Cached values survive
// popup close/reopen cycles for the lifetime of the page.
type VenueHoursPayload = {
  openNow: boolean | null;
  closesAt: string | null;
  week: { open: string; close: string }[][] | null;
} | null;
const venuePhotoCache = new Map<string, string | null>();
const venueHoursCache = new Map<string, VenueHoursPayload>();

/**
 * Single source of truth for "what should this marker look like for the
 * current (hour, filter, weather)" — used both by the hour-update effect
 * (mutating ~2 500 existing markers) and by viewport culling (applying
 * state to a marker we just added back to the map after panning).
 */
function computeMarkerState(
  venue: any,
  dateKey: string,
  hour: number,
  filter: "all" | "sun" | "shade",
  weather: WeatherData | null,
): { className: string; visible: boolean } {
  const status = normalize(getStatus(venue, dateKey, hour));
  const wSymbol = weather?.hourly[hour]?.symbolCode;
  const isRain = wSymbol !== undefined && getSymbolInfo(wSymbol).category === "rain";

  let className: string;
  if (isRain) className = "marker-rain";
  else if (status === "sun" && wSymbol !== undefined && wSymbol <= 2) className = "marker-sun";
  else if (status === "sun" && wSymbol !== undefined && wSymbol <= 4) className = "marker-partial";
  else if (status === "sun") className = "marker-sun";
  else className = "marker-shade";

  const visible =
    filter === "all" ||
    (filter === "sun" && status === "sun") ||
    (filter === "shade" && (status === "shade" || status === "night"));

  return { className, visible };
}

/** Push the (className, visible) pair onto a marker's existing DOM. */
function applyMarkerVisualState(marker: L.Marker, state: { className: string; visible: boolean }) {
  const iconEl = (marker as any)._icon as HTMLElement | undefined;
  if (!iconEl) return;
  const dot = iconEl.firstElementChild as HTMLElement | null;
  if (dot) dot.className = `marker-dot ${state.className}`;
  iconEl.style.display = state.visible ? "" : "none";
}

/**
 * Render a venue's photo into `container`. Checks the photo cache first;
 * fetches `/api/venue-photo` only on the very first open per page session.
 * Required because lazy popups regenerate DOM on each open, defeating the
 * old `dataset.loaded` flag that the persistent-DOM version relied on.
 */
function renderVenuePhoto(container: HTMLElement, venue: any) {
  const cached = venuePhotoCache.get(venue.id);
  if (cached !== undefined) {
    // Already handled in buildVenuePopupHtml — image embedded in HTML or no container rendered.
    return;
  }
  const params = new URLSearchParams({
    id: venue.id, name: venue.name, lat: String(venue.lat), lng: String(venue.lng), type: venue.type,
  });
  fetch(`/api/venue-photo?${params}`)
    .then((r) => r.ok ? r.json() : null)
    .then((data) => {
      const url = (data?.photoUrl ?? null) as string | null;
      venuePhotoCache.set(venue.id, url);
      if (url) {
        container.innerHTML = `<img src="${url}" alt="${venue.name}" style="width:100%;height:100%;object-fit:cover;display:block" loading="lazy" />`;
      } else {
        container.style.cssText += ";height:0;margin-top:0;margin-bottom:0;display:none";
      }
    })
    .catch(() => {});
}

/** Render an opening-hours block from `/api/venue-hours`, with cache. */
function renderVenueHours(container: HTMLElement, venue: any) {
  const inject = (data: VenueHoursPayload) => {
    if (!data || (data.openNow === null && !data.week)) return;
    const DAYS = ["Mån", "Tis", "Ons", "Tor", "Fre", "Lör", "Sön"];
    const todayMon0 = (new Date().getDay() + 6) % 7;
    const dotColor = data.openNow ? "#10b981" : data.openNow === false ? "#ef4444" : "#94a3b8";

    // Compute next opening time when closed
    let opensAt: string | null = null;
    if (data.openNow === false && data.week) {
      const now = new Date();
      const todayMon0 = (now.getDay() + 6) % 7;
      const pad = (n: number) => String(n).padStart(2, "0");
      const currentTime = `${pad(now.getHours())}:${pad(now.getMinutes())}`;
      const DAYS_SHORT = ["mån", "tis", "ons", "tor", "fre", "lör", "sön"];
      outer: for (let d = 0; d <= 7; d++) {
        const dayIdx = (todayMon0 + d) % 7;
        const segs = data.week[dayIdx] || [];
        for (const seg of segs) {
          if (d === 0 && seg.open <= currentTime) continue;
          opensAt = d === 0 ? `kl. ${seg.open}` : d === 1 ? `imorgon kl. ${seg.open}` : `${DAYS_SHORT[dayIdx]} kl. ${seg.open}`;
          break outer;
        }
      }
    }

    const statusText = data.openNow
      ? `Öppet${data.closesAt ? ` — stänger ${data.closesAt}` : ""}`
      : data.openNow === false
        ? `Stängt${opensAt ? ` — öppnar ${opensAt}` : " just nu"}`
        : "Öppettider";

    const weekRows = data.week?.map((segments, i) => {
      const isToday = i === todayMon0;
      const timeText = segments.length
        ? segments.map((s) => `${s.open}–${s.close}`).join(", ")
        : "Stängt";
      const closed = segments.length === 0;
      return `
        <div class="venue-hours-row${isToday ? " venue-hours-row-today" : ""}">
          <span class="venue-hours-day">${DAYS[i]}</span>
          <span class="venue-hours-time${closed ? " venue-hours-closed" : ""}">${timeText}</span>
        </div>
      `;
    }).join("") ?? "";

    const weekHtml = data.week && data.week.length
      ? `<div class="venue-hours-week" style="display:none">${weekRows}</div>`
      : "";

    container.innerHTML = `
      <div class="venue-hours-status">
        <span class="venue-hours-dot" style="background:${dotColor}"></span>
        <span class="venue-hours-status-text">${statusText}</span>
        ${weekHtml ? `<button class="hours-toggle" aria-expanded="false">
          <svg class="hours-toggle-caret" width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M2 3.5L5 6.5L8 3.5" /></svg>
        </button>` : ""}
      </div>
      ${weekHtml}
    `;

    const toggle = container.querySelector<HTMLButtonElement>(".hours-toggle");
    const week = container.querySelector<HTMLDivElement>(".venue-hours-week");
    if (toggle && week) {
      toggle.onclick = () => {
        const visible = week.style.display !== "none";
        week.style.display = visible ? "none" : "block";
        toggle.setAttribute("aria-expanded", visible ? "false" : "true");
      };
    }
  };

  if (venueHoursCache.has(venue.id)) {
    inject(venueHoursCache.get(venue.id) as VenueHoursPayload);
    return;
  }
  const params = new URLSearchParams({
    id: venue.id, name: venue.name, lat: String(venue.lat), lng: String(venue.lng), type: venue.type,
  });
  fetch(`/api/venue-hours?${params}`)
    .then((r) => r.ok ? r.json() : null)
    .then((data: VenueHoursPayload) => {
      venueHoursCache.set(venue.id, data);
      inject(data);
    })
    .catch(() => {});
}

/**
 * Builds popup HTML for a confirmed venue. Called lazily by Leaflet on
 * popupopen — paying the ~3–5 KB string + 16-hour `getBestHour` loop only
 * for the venue the user actually opens. Keeps the build effect from
 * pre-allocating ~25 MB of popup strings for 2 500 venues, and means the
 * "current hour" highlight is always fresh (not frozen at build time).
 */
function buildVenuePopupHtml(
  venue: any,
  dateKey: string,
  hour: number,
  weather: WeatherData | null,
): string {
  const status = normalize(getStatus(venue, dateKey, hour));
  const sunHours = getSunHrs(venue, dateKey);
  const hours = Array.from({ length: 16 }, (_, i) => i + 7);

  const shadowTimeline = hours
    .map((h) => {
      const s = normalize(getStatus(venue, dateKey, h));
      let bg: string;
      if (s === "sun") {
        const dist = Math.abs(h - 13);
        if (dist >= 6) bg = "background:linear-gradient(180deg,#fef9c3,#fde68a)";
        else if (dist >= 4) bg = "background:linear-gradient(180deg,#fde68a,#fbbf24)";
        else if (dist >= 2) bg = "background:linear-gradient(180deg,#fbbf24,#f59e0b)";
        else bg = "background:linear-gradient(180deg,#f59e0b,#ea580c)";
      } else {
        bg = s === "partial" ? "background:linear-gradient(135deg,#fed7aa,#fb923c)"
           : s === "night" ? "background:#1e293b"
           : "background:#e2e8f0";
      }
      const isCurrent = h === hour;
      const barH = isCurrent ? "height:20px" : "height:16px";
      const glow = isCurrent && (s === "sun" || s === "partial") ? ";box-shadow:0 0 8px rgba(245,158,11,0.65)" : "";
      return `<div style="flex:1;border-radius:4px;${bg};${barH}${glow};min-width:0" title="${h}:00 — ${statusToLabel(s)}"></div>`;
    })
    .join("");

  const hourLabels = hours
    .map((h) => {
      const bold = h === hour ? "font-weight:700;color:#334155" : "";
      return `<div style="flex:1;text-align:center;font-size:6px;color:#94a3b8;min-width:0;${bold}">${h}</div>`;
    })
    .join("");

  const nowDots = hours
    .map((h) =>
      h === hour
        ? `<div style="flex:1;min-width:0;display:flex;justify-content:center"><div style="width:5px;height:5px;border-radius:50%;background:#f59e0b;box-shadow:0 0 4px rgba(245,158,11,0.7)"></div></div>`
        : `<div style="flex:1;min-width:0"></div>`
    )
    .join("");

  const bestHour = getBestHour(venue, dateKey, weather);
  const bestHourLine = bestHour
    ? `<div style="border-left:3px solid #f59e0b;padding:3px 8px;margin-top:6px;background:#fffbeb;border-radius:0 6px 6px 0;display:flex;align-items:center;gap:5px">
        <span style="font-size:11px">&#11088;</span>
        <span style="font-size:11px;color:#78350f;font-weight:500">B&auml;sta timmen: ${bestHour.label}</span>
      </div>`
    : "";

  const ratingHtml = venue.rating != null
    ? `&#11088; ${venue.rating.toFixed(1)}${venue.ratingCount != null ? `<span style="color:#b0bec5"> (${venue.ratingCount.toLocaleString("sv-SE")})</span>` : ""} &middot; `
    : "";

  const cachedPhoto = venuePhotoCache.get(venue.id);
  const photoContainerHtml = cachedPhoto === null
    ? ""
    : `<div id="venue-photo-${venue.id}" style="margin:-12px -16px 10px -16px;height:140px;background:linear-gradient(180deg,#f1f5f9,#e2e8f0);border-radius:12px 12px 0 0;overflow:hidden">${cachedPhoto ? `<img src="${cachedPhoto}" alt="${venue.name}" style="width:100%;height:100%;object-fit:cover;display:block" loading="lazy" />` : ""}</div>`;

  const mapUrl = `https://www.google.com/maps/place/${encodeURIComponent(venue.name)}/@${venue.lat},${venue.lng},17z`;

  return `
    <div style="min-width:260px">
      ${photoContainerHtml}
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <strong style="font-size:17px;line-height:1.2;flex:1;margin-right:6px">${venue.name}</strong>
        <span style="font-size:20px;flex-shrink:0">${statusToEmoji(status)}</span>
      </div>
      <div style="font-size:11px;color:#94a3b8;margin-top:2px">${ratingHtml}${typeToLabel(venue.type)}</div>
      <div id="venue-hours-${venue.id}" style="margin-top:6px"></div>
      <div style="background:#f8fafc;border-radius:8px;padding:5px 6px;margin-top:8px">
        <div style="display:flex;gap:2px;align-items:flex-end">${shadowTimeline}</div>
        <div style="display:flex;gap:2px;margin-top:2px">${hourLabels}</div>
        <div style="display:flex;gap:2px;margin-top:1px">${nowDots}</div>
        <div style="font-size:10px;color:#94a3b8;text-align:right;margin-top:2px">${sunHours} soltimmar</div>
      </div>
      ${bestHourLine}
      <div style="display:flex;align-items:center;gap:6px;margin-top:8px">
        <button
          class="fav-btn"
          data-venue-id="${venue.id}"
          style="flex:0 0 32px;height:32px;border:1px solid #fecaca;border-radius:8px;background:#fff;color:#ef4444;font-size:16px;cursor:pointer;display:flex;align-items:center;justify-content:center"
          title="Spara som favorit"
        >${getFavorites().has(venue.id) ? "&#10084;&#65039;" : "&#9825;"}</button>
        <a
          href="${mapUrl}"
          target="_blank"
          rel="noopener noreferrer"
          title="Öppna i Google Maps"
          style="flex:0 0 32px;height:32px;border:1px solid #e2e8f0;border-radius:8px;background:#fff;display:flex;align-items:center;justify-content:center;text-decoration:none"
        ><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z" fill="#EA4335"/><circle cx="12" cy="9" r="2.5" fill="#fff"/></svg></a>
        <button
          class="share-btn"
          data-venue-id="${venue.id}"
          data-venue-name="${venue.name}"
          style="flex:1;height:32px;border:none;border-radius:8px;background:#f59e0b;color:#fff;font-size:11px;font-weight:600;cursor:pointer"
        >&#128279; Dela</button>
      </div>
      <div style="text-align:right;margin-top:4px">
        <button
          class="feedback-btn"
          data-venue-id="${venue.id}"
          style="border:none;background:none;color:#cbd5e1;font-size:10px;cursor:pointer;text-decoration:underline;text-underline-offset:2px;padding:0"
        >St&auml;mmer inte?</button>
      </div>
    </div>
  `;
}

export default function SunMap({ hour: hourProp, date, filter, typeFilter, sunRange, weather, onFeedback, showShadows, showMetro, focusVenueId, onFocusHandled, metroStation }: SunMapProps) {
  // Defer expensive map rebuild while the user is actively scrubbing the timeline
  const hour = useDeferredValue(hourProp);

  const mapRef = useRef<L.Map | null>(null);
  const markersRef = useRef<L.Marker[]>([]);
  // Parallel array of (marker, venue) so the hour-update effect can recompute
  // status without rebuilding markers. Kept in lockstep with markersRef.
  const markerVenuesRef = useRef<{ marker: L.Marker; venue: any }[]>([]);
  // Weather snapshot read by the hour-update effect (avoids making `weather`
  // a dep of the cheap update path — only the build effect rebuilds on weather).
  const weatherRef = useRef<WeatherData | null>(null);
  weatherRef.current = weather;
  // Latest hour for popup handlers (e.g. share-link) attached at build time.
  const hourRef = useRef(0);
  hourRef.current = hourProp;
  // Latest filter so cull-on-pan can apply correct visibility to markers
  // that re-enter the viewport without going through the hour-update effect.
  const filterRef = useRef<"all" | "sun" | "shade">("all");
  filterRef.current = filter;
  const unconfirmedMarkersRef = useRef<L.Marker[]>([]);
  const metroMarkersRef = useRef<L.Marker[]>([]);
  const metroNetworkRef = useRef<L.LayerGroup | null>(null);
  const metroDetailRef = useRef<L.LayerGroup | null>(null);
  // Chaikin-smoothed tracks — computed once, shared between render and snapToTrack
  const smoothedTracksRef = useRef<{ color: "red" | "green" | "blue"; coords: [number, number][] }[]>([]);
  // Station snaps with neighbor-corrected directions — shared between main + detail layer
  const stationSnapsRef = useRef<(SnapResult & { station: { lat: number; lng: number; name: string } })[]>([]);
  const shadowLayerRef = useRef<L.GeoJSON | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const userMarkerRef = useRef<L.Marker | null>(null);
  const geoWatchRef = useRef<number | null>(null);
  const hasCenteredRef = useRef(false);
  const [geoState, setGeoState] = useState<"idle" | "locating" | "located" | "error">("idle");
  const [searchOpen, setSearchOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const searchRef = useRef<HTMLDivElement>(null);

  const dateKey = useMemo(() => getDateKey(date), [date]);

  // Initialize map
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return;

    const map = L.map(containerRef.current, {
      center: [59.325, 18.07],
      zoom: 13,
      zoomControl: false,
    });

    L.tileLayer(
      "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
      {
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OSM</a> &copy; <a href="https://carto.com/">CARTO</a>',
        maxZoom: 19,
        // Load tiles immediately during pan (not just after pan ends).
        // Default on mobile is true which causes blank tiles during drag.
        updateWhenIdle: false,
        // Pre-fetch 4 extra tile columns/rows beyond the visible viewport so
        // they're already loaded when the user pans into that area.
        // Default is 2; 4–5 eliminates most blank-tile flashes on fast pans.
        keepBuffer: 5,
      }
    ).addTo(map);


    map.on("zoomend", () => {
      const container = map.getContainer();
      container.classList.toggle("show-badges", map.getZoom() >= 17);
      // Trigger unconfirmed venue rendering on zoom change
      map.fire("update-unconfirmed");
    });

    map.on("moveend", () => {
      map.fire("update-unconfirmed");
    });

    mapRef.current = map;

    return () => {
      map.remove();
      mapRef.current = null;
    };
  }, []);

  // Metro tracks + platforms layer — toggleable via showMetro prop
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    // Always tear down before deciding whether to redraw — keeps state predictable
    if (metroNetworkRef.current) {
      metroNetworkRef.current.remove();
      metroNetworkRef.current = null;
    }

    if (!showMetro || !metroNetwork) return;

    const lineColors: Record<"red" | "green" | "blue", string> = {
      red: "#e3000b",
      green: "#00a14e",
      blue: "#0065bd",
    };
    const HALF_M = 65; // 130m platform

    // 1. Chaikin-utjämnade spår + lateral offset per linjefärg
    //    Röd: +10m (höger), Grön: -10m (vänster), Blå: 0m
    //    Separerar parallella linjer (Slussen, Gamla Stan, T-Centralen)
    const LATERAL: Record<"red" | "green" | "blue", number> = { red: 10, green: -10, blue: 0 };
    const smoothed = metroNetwork.METRO_TRACKS.map((t) => ({
      color: t.color,
      coords: applyLateralOffset(chaikin(t.coords as [number, number][], 3), LATERAL[t.color]),
    }));
    smoothedTracksRef.current = smoothed;

    // 2. Förutberäkna kumulativa avstånd per spår (används av interpAtDist)
    const cumDists = smoothed.map((track) => {
      const midLat = track.coords[Math.floor(track.coords.length / 2)][0];
      const cosLat = Math.cos((midLat * Math.PI) / 180);
      return buildCumDist(track.coords, cosLat);
    });

    // 3. Snap alla stationer mot de utjämnade (offset) spåren (ger trackIdx + segIdx)
    const rawSnaps = metroNetwork.METRO_STATIONS.map((s) => ({
      station: s,
      ...snapToTrack(s.lat, s.lng, smoothed),
    }));

    // 4. Grann-baserad riktning (dir = normalize(next - prev) längs spåret)
    const byTrack = new Map<number, typeof rawSnaps>();
    for (const snap of rawSnaps) {
      if (!byTrack.has(snap.trackIdx)) byTrack.set(snap.trackIdx, []);
      byTrack.get(snap.trackIdx)!.push(snap);
    }
    for (const group of byTrack.values()) {
      group.sort((a, b) => a.segIdx - b.segIdx);
      for (let i = 0; i < group.length; i++) {
        const prev = group[Math.max(0, i - 1)];
        const next = group[Math.min(group.length - 1, i + 1)];
        if (prev === next) continue;
        const cosLat = Math.cos(group[i].pos[0] * Math.PI / 180);
        const dLat = next.pos[0] - prev.pos[0], dLng = next.pos[1] - prev.pos[1];
        const norm = Math.hypot(dLat, dLng * cosLat) || 1;
        group[i].dir = [dLat / norm, dLng / norm];
      }
    }

    // 5. Beräkna pa/pb via interpAtDist på det OFFSET-spåret → perfekt tangent-alignment.
    //    platDir = normalize(pb - pa): exakt i linje med det renderade spåret, inga "knän".
    for (const snap of rawSnaps) {
      const cumDist = cumDists[snap.trackIdx];
      const trackCoords = smoothed[snap.trackIdx].coords;
      const totalLen = cumDist[cumDist.length - 1];
      const stDist = cumDist[snap.segIdx];
      const pa = interpAtDist(trackCoords, cumDist, Math.max(0, stDist - HALF_M));
      const pb = interpAtDist(trackCoords, cumDist, Math.min(totalLen, stDist + HALF_M));
      const cosLat = Math.cos(snap.pos[0] * Math.PI / 180);
      const dLat = pb[0] - pa[0], dLng = pb[1] - pa[1];
      const normLen = Math.hypot(dLat, dLng * cosLat) || 1;
      snap.pa = pa;
      snap.pb = pb;
      snap.platDir = [dLat / normLen, dLng / normLen];
    }

    const allSnaps = Array.from(byTrack.values()).flat();
    stationSnapsRef.current = allSnaps;

    // 4. Bygg "plattformiserade" spår: rak linje GENOM varje station, kurvor MELLAN.
    //    Inkludera ALLA stationer med samma färg som ligger inom 150m av spåret —
    //    inte bara de som snappade till just detta spår. Det innebär att t.ex. Mariatorget
    //    klipps korrekt på båda T13 och T14, utan att överbara stationer på andra grenar stör.
    const platformized = smoothed.map((track) => {
      const midLat = track.coords[Math.floor(track.coords.length / 2)][0];
      const cosLat = Math.cos((midLat * Math.PI) / 180);
      const DIST_THRESHOLD = 150; // meter

      const stationsForThisTrack = allSnaps
        .filter((s) => s.color === track.color &&
          approxDistToTrack(s.pos[0], s.pos[1], track.coords, cosLat) < DIST_THRESHOLD)
        .map((s) => ({ pos: s.pos, dir: s.dir }));

      return { color: track.color, coords: platformizeTrack(track.coords, stationsForThisTrack, HALF_M) };
    });

    const layer = L.layerGroup();

    // Egen pane för korridorer — under spår (overlayPane 400) men över vägnätet (tilePane 200)
    if (!map.getPane("metroCorridorPane")) {
      const corridorPane = map.createPane("metroCorridorPane");
      corridorPane.style.zIndex = "395";
      corridorPane.style.pointerEvents = "none";
    }

    // Station→snap lookup: pa/pb är perrongens ändpunkter, så vi kan rita
    //    varje uppgång från NÄRMASTE punkt på perrongkanten (inte centerstrålning)
    type SnapInfo = { pa: [number, number]; pb: [number, number]; color: string };
    const stationSnapMap = new Map<string, SnapInfo>();
    for (const snap of allSnaps) {
      if (snap.pa && snap.pb) {
        stationSnapMap.set(`${snap.station.lat},${snap.station.lng}`, {
          pa: snap.pa, pb: snap.pb, color: lineColors[snap.color],
        });
      }
    }

    // Upplysta gångar: en separat linje per uppgång, från närmaste punkt på
    //    perrongen → entrén. Vit glow under, färgad linje över.
    for (const ent of metroNetwork.METRO_ENTRANCES) {
      const info = stationSnapMap.get(`${ent.link[0][0]},${ent.link[0][1]}`);
      const lc = info?.color ?? "#64748b";
      const startPt: [number, number] = info
        ? nearestOnSegment(ent.lat, ent.lng, info.pa, info.pb)
        : (ent.link[0] as [number, number]);
      const corridor: [[number, number], [number, number]] = [startPt, [ent.lat, ent.lng]];

      // Vit glow (under) — bredare så den sticker ut 2px på varje sida
      L.polyline(corridor, {
        color: "#ffffff", weight: 8, opacity: 0.55,
        lineCap: "round", interactive: false,
        pane: "metroCorridorPane",
      }).addTo(layer);
      // Färgad korridor (över) — 4px, 40% opacity i linjefärgen
      L.polyline(corridor, {
        color: lc, weight: 4, opacity: 0.4,
        lineCap: "round", interactive: false,
        pane: "metroCorridorPane",
      }).addTo(layer);
    }

    // Spår — plattformiserade (raka vid stationer, kurvor mellan)
    for (const track of platformized) {
      L.polyline(track.coords, {
        color: lineColors[track.color], weight: 4, opacity: 0.85,
        lineCap: "round", lineJoin: "round", smoothFactor: 0, interactive: false,
      }).addTo(layer);
    }

    // Stationscirklar ovanpå spåren
    for (const { pos, color } of allSnaps) {
      L.circleMarker(pos, {
        radius: 5, color: lineColors[color], weight: 2.5,
        fillColor: "#ffffff", fillOpacity: 1, interactive: false,
      }).addTo(layer);
    }

    // Entré-ikoner: vit cirkel + färgad ring + ↑
    for (const ent of metroNetwork.METRO_ENTRANCES) {
      const lc = stationSnapMap.get(`${ent.link[0][0]},${ent.link[0][1]}`)?.color ?? "#64748b";
      const titleAttr = ent.name ? ` title="${ent.name.replace(/"/g, "&quot;")}"` : "";
      const entranceIcon = L.divIcon({
        className: "metro-entrance",
        html: `<div class="metro-entrance-dot" style="--lc:${lc}"${titleAttr}>↑</div>`,
        iconSize: [14, 14],
        iconAnchor: [7, 7],
      });
      L.marker([ent.lat, ent.lng], { icon: entranceIcon, interactive: !!ent.name, zIndexOffset: -50 })
        .addTo(layer);
    }

    layer.addTo(map);
    metroNetworkRef.current = layer;

    return () => {
      if (metroNetworkRef.current) {
        metroNetworkRef.current.remove();
        metroNetworkRef.current = null;
      }
    };
  }, [showMetro]);

  // Zoom-dependent metro detail: platform + station name + T-markers with exit names
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !metroNetwork) return;

    const LINE_COLORS = { red: "#e3000b", green: "#00a14e", blue: "#0065bd" } as const;

    // Pre-group entrances by station position (link[0] = station center)
    const entrancesByStation = new Map<string, typeof metroNetwork.METRO_ENTRANCES[number][]>();
    for (const ent of metroNetwork.METRO_ENTRANCES) {
      const key = `${ent.link[0][0]},${ent.link[0][1]}`;
      if (!entrancesByStation.has(key)) entrancesByStation.set(key, []);
      entrancesByStation.get(key)!.push(ent);
    }

    // Use pre-computed snaps with neighbor-corrected directions from main layer
    const stationSnaps = stationSnapsRef.current;

    function buildDetailLayer(zoom: number) {
      if (metroDetailRef.current) {
        metroDetailRef.current.remove();
        metroDetailRef.current = null;
      }
      if (!showMetro || !mapRef.current) return;
      if (zoom < 15) return;

      const showNames = zoom >= 16;
      const detail = L.layerGroup();
      const HALF_M = 65;

      // Eget Leaflet-pane för stationsmarkörer — renderas ovanför spår och perronger
      if (!mapRef.current.getPane("metroStationPane")) {
        const pane = mapRef.current.createPane("metroStationPane");
        pane.style.zIndex = "620"; // över overlayPane (400) och markerPane (600)
      }
      // Korridorpane — under spår (400) men över vägnätet (200)
      if (!mapRef.current.getPane("metroCorridorPane")) {
        const corridorPane = mapRef.current.createPane("metroCorridorPane");
        corridorPane.style.zIndex = "395";
        corridorPane.style.pointerEvents = "none";
      }

      for (const { station, pos, color, pa, pb, platDir } of stationSnaps) {
        const lc = LINE_COLORS[color];
        // Använd pa/pb från interpAtDist på det offset-spåret →
        // perfekt tangent-alignment, inga "knän" vid perrongänden
        const p1 = pa ?? offsetAlongDir(pos, platDir ?? [1,0], -HALF_M);
        const p2 = pb ?? offsetAlongDir(pos, platDir ?? [1,0],  HALF_M);

        // Rakt spårsegment GENOM stationen (överskriver Chaikin-kurvan precis här)
        L.polyline([p1, p2], { color: lc, weight: 4, opacity: 0.85, lineCap: "butt", smoothFactor: 0, interactive: false }).addTo(detail);

        // Platform: subtil skugga → färgad ytterkant → vit inre
        // Bredare än spårlinjen (4px) → tydlig perrong-form
        L.polyline([p1, p2], { color: "#0f172a", weight: 16, opacity: 0.12, lineCap: "round", smoothFactor: 0, interactive: false }).addTo(detail);
        L.polyline([p1, p2], { color: lc,      weight: 13, lineCap: "round", smoothFactor: 0, interactive: false }).addTo(detail);
        L.polyline([p1, p2], { color: "#ffffff", weight: 9,  lineCap: "round", smoothFactor: 0, interactive: false }).addTo(detail);

        // Centroid p1→p2 (mer exakt än `pos` som är GTFS stop-centroid)
        const midPt: [number, number] = [(p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2];

        if (showNames) {
          // T-ikon: centrerad på midPt, i det egna överpanelet
          const tIcon = L.divIcon({
            className: "metro-t-wrap",
            html: `<div class="metro-t-circle" style="background:${lc}">T</div>`,
            iconSize: [20, 20],
            iconAnchor: [10, 10],
          });
          L.marker(midPt, { icon: tIcon, interactive: false, pane: "metroStationPane" }).addTo(detail);

          // Stationsnamn: T-cirkel är 20px hög (10px upp/ner från center).
          // iconAnchor [100, -13] → toppen av name-boxen placeras 13px under midPt,
          // dvs 3px gap under T-cirkelns botten (10px + 3px = 13px).
          const nameIcon = L.divIcon({
            className: "metro-platform-label",
            html: `<div class="metro-platform-name" style="--lc:${lc}">${station.name}</div>`,
            iconSize: [200, 16],
            iconAnchor: [100, -13],
          });
          L.marker(midPt, { icon: nameIcon, interactive: false, pane: "metroStationPane" }).addTo(detail);
        }

        // Uppgångar: upplysta gångar (glow + corridor) + T-ring entré.
        // Bara exit-namn om det skiljer sig från stationsnamnet (undviker upprepning).
        const key = `${station.lat},${station.lng}`;
        const entrances = entrancesByStation.get(key) ?? [];
        for (const ent of entrances) {
          const nearPt = nearestOnSegment(ent.lat, ent.lng, p1, p2);

          // Vit glow (under) — bredare för att simulera upplyst gång
          L.polyline([nearPt, [ent.lat, ent.lng]], {
            color: "#ffffff", weight: 8, opacity: 0.55,
            lineCap: "round", interactive: false,
            pane: "metroCorridorPane",
          }).addTo(detail);

          // Färgad korridor (över) — 4px, 40% opacity
          L.polyline([nearPt, [ent.lat, ent.lng]], {
            color: lc, weight: 4, opacity: 0.4,
            lineCap: "round", interactive: false,
            pane: "metroCorridorPane",
          }).addTo(detail);

          // Entré-ikon: vit cirkel med färgad ring + ↑
          const entranceIcon = L.divIcon({
            className: "metro-entrance",
            html: `<div class="metro-entrance-dot metro-entrance-dot--lg" style="--lc:${lc}">↑</div>`,
            iconSize: [18, 18],
            iconAnchor: [9, 9],
          });
          L.marker([ent.lat, ent.lng], { icon: entranceIcon, interactive: false }).addTo(detail);

          // Namn-label bara om det är ett unikt gatunamn (inte stationsnamnet)
          const entNameClean = ent.name.toLowerCase().trim();
          const stationNameClean = station.name.toLowerCase().trim();
          if (showNames && ent.name && !entNameClean.startsWith(stationNameClean)) {
            const exitLabel = L.divIcon({
              className: "metro-exit-label",
              html: `<span class="metro-exit-name">${ent.name}</span>`,
              // Höger om ikonen (14px) + halo (2px) + 2px gap → x = -13.
              //    Vertikalt centrerat på ikonen (label ~12px hög) → y = 6.
              iconAnchor: [-13, 6],
            });
            L.marker([ent.lat, ent.lng], { icon: exitLabel, interactive: false }).addTo(detail);
          }
        }
      }

      detail.addTo(mapRef.current!);
      metroDetailRef.current = detail;
    }

    const onZoom = () => { if (mapRef.current) buildDetailLayer(mapRef.current.getZoom()); };
    map.on("zoomend", onZoom);
    buildDetailLayer(map.getZoom());

    return () => {
      map.off("zoomend", onZoom);
      if (metroDetailRef.current) { metroDetailRef.current.remove(); metroDetailRef.current = null; }
    };
  }, [showMetro]);

  // Metro station markers — visible at same zoom as venue badges
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    metroMarkersRef.current.forEach((m) => m.remove());
    metroMarkersRef.current = [];

    for (const station of METRO_STATIONS) {
      const lineColor = station.lines.includes("red") ? "#e3000b"
        : station.lines.includes("green") ? "#00a14e"
        : "#0065bd";

      const icon = L.divIcon({
        className: "metro-marker",
        html: `<div class="metro-icon" style="--line-color:${lineColor}">
          <div class="metro-dot" style="background:${lineColor}">T</div>
          <span class="metro-label">${station.name}</span>
        </div>`,
        iconSize: [20, 20],
        iconAnchor: [10, 10],
      });

      const marker = L.marker([station.lat, station.lng], { icon, interactive: false, zIndexOffset: -100 }).addTo(map);
      metroMarkersRef.current.push(marker);
    }

    return () => {
      metroMarkersRef.current.forEach((m) => m.remove());
      metroMarkersRef.current = [];
    };
  }, []);

  // Build venue markers — runs only when the *set* of venues or their styling
  // baseline changes (date, type/sunRange filters, weather, metroStation).
  // Hour scrubs and sun/shade filter changes go through the cheap update effect
  // below, which retoggles `.marker-dot`'s class on the existing DOM rather
  // than tearing down ~2 500 Leaflet markers.
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    markersRef.current.forEach((m) => m.remove());
    markersRef.current = [];
    markerVenuesRef.current = [];

    allVenues.forEach((venue: any) => {
      // Filter by metro station proximity
      if (metroStation) {
        const dist = distanceM(venue.lat, venue.lng, metroStation.lat, metroStation.lng);
        if (dist > STATION_RADIUS_M) return;
      }

      // Filter by type
      if (!matchesTypeFilter(venue, typeFilter)) return;

      // Sun/shade filter intentionally NOT applied here — the update effect
      // below toggles visibility based on the live (hour, filter) pair so
      // scrubbing the timeline doesn't rebuild markers.

      // Filter by sun range — venue must have sun for every hour in the range
      if (sunRange) {
        let hasSunAllHours = true;
        for (let h = sunRange.from; h <= sunRange.to; h++) {
          const s = normalize(getStatus(venue, dateKey, h));
          if (s !== "sun") { hasSunAllHours = false; break; }
        }
        if (!hasSunAllHours) return;
      }

      // Initial state seeded into the divIcon HTML — overwritten by
      // applyMarkerVisualState the moment the cull function adds this marker
      // to the map (or by the hour-update effect on subsequent ticks).
      const initial = computeMarkerState(venue, dateKey, hour, filter, weather);
      const markerClass = initial.className;

      const svgIcon = typeToSvgIcon(venue.type);
      const shortName = venue.name.length > 20 ? venue.name.slice(0, 18) + "…" : venue.name;
      const sunPeriod = getSunPeriod(venue, dateKey);
      const badgeHtml = svgIcon ? `
        <div class="marker-badge badge-above">
          <div class="marker-badge-icon">${svgIcon}</div>
          <div class="marker-badge-text">
            <div class="marker-badge-name">${shortName}</div>
            <div class="marker-badge-sun">${sunPeriod}</div>
          </div>
          <div class="marker-badge-arrow"></div>
        </div>` : "";
      // Uniform 18px wrapper — the dot's visual size is keyed off its status
      // class in CSS, so flipping marker-shade <-> marker-sun on hour change
      // doesn't require resizing the Leaflet icon container.
      const ICON_SIZE = 18;
      const icon = L.divIcon({
        className: "marker-root",
        html: `<div class="marker-dot ${markerClass}"></div>${badgeHtml}`,
        iconSize: [ICON_SIZE, ICON_SIZE],
        iconAnchor: [ICON_SIZE / 2, ICON_SIZE / 2],
        popupAnchor: [0, -ICON_SIZE / 2 - 4],
      });

      // Popup HTML is built lazily on open via the function form of bindPopup.
      // The function reads hour/weather from refs so it always reflects the
      // current slider state — no stale "current hour" highlight.
      // Marker is NOT added to the map here; cullToViewport (below) only
      // adds markers that are actually inside the buffered viewport.
      const marker = L.marker([venue.lat, venue.lng], { icon }).bindPopup(
        () => buildVenuePopupHtml(venue, dateKey, hourRef.current, weatherRef.current),
        { maxWidth: 300 },
      );

      marker.on("popupopen", () => {
        // Favorite button
        const favBtn = document.querySelector(`.fav-btn[data-venue-id="${venue.id}"]`);
        if (favBtn) {
          (favBtn as HTMLElement).onclick = () => {
            const favs = toggleFavorite(venue.id);
            (favBtn as HTMLElement).innerHTML = favs.has(venue.id) ? "\u2764\uFE0F" : "\u2661";
          };
        }

        // Photo + hours render through cached helpers — fetch happens at most
        // once per venue per page session, regardless of how many times the
        // user opens this popup.
        const photoContainer = document.getElementById(`venue-photo-${venue.id}`);
        if (photoContainer) renderVenuePhoto(photoContainer, venue);

        const hoursContainer = document.getElementById(`venue-hours-${venue.id}`);
        if (hoursContainer) renderVenueHours(hoursContainer, venue);

        // Share button
        const shareBtn = document.querySelector(`.share-btn[data-venue-id="${venue.id}"]`);
        if (shareBtn) {
          (shareBtn as HTMLElement).onclick = () => {
            const url = new URL(window.location.href);
            url.search = "";
            url.searchParams.set("venue", venue.id);
            url.searchParams.set("hour", String(hourRef.current));
            const shareUrl = url.toString();

            if (navigator.share) {
              navigator.share({ title: `${venue.name} — Soldryck`, text: `Se solläget på ${venue.name}!`, url: shareUrl });
            } else {
              navigator.clipboard.writeText(shareUrl).then(() => {
                (shareBtn as HTMLElement).textContent = "Kopierad!";
                setTimeout(() => { (shareBtn as HTMLElement).innerHTML = "&#128279; Dela"; }, 2000);
              });
            }
          };
        }

        // Feedback button
        const btn = document.querySelector(`.feedback-btn[data-venue-id="${venue.id}"]`);
        if (btn && onFeedback) {
          (btn as HTMLElement).onclick = () => {
            const currentSchedule: Record<number, "sun" | "shade" | "night"> = {};
            for (let h = 7; h <= 22; h++) {
              currentSchedule[h] = normalize(getStatus(venue, dateKey, h)) as "sun" | "shade" | "night";
            }
            onFeedback({
              id: venue.id,
              name: venue.name,
              type: venue.type,
              currentSchedule,
            });
            map.closePopup();
          };
        }
      });

      markersRef.current.push(marker);
      markerVenuesRef.current.push({ marker, venue });
    });

    // Viewport culling — only ~200–500 markers (those visible + a 30 % buffer)
    // are actually attached to the map. Off-screen markers stay as L.Marker
    // objects in memory but contribute zero DOM nodes / zero zoom-recompute
    // cost. The buffer is wide enough that fast pans don't reveal blank
    // tiles before moveend fires.
    function cullToViewport() {
      const m = mapRef.current;
      if (!m) return;
      const bounds = m.getBounds();
      const latBuf = (bounds.getNorth() - bounds.getSouth()) * 0.3;
      const lngBuf = (bounds.getEast() - bounds.getWest()) * 0.3;
      const south = bounds.getSouth() - latBuf;
      const north = bounds.getNorth() + latBuf;
      const west = bounds.getWest() - lngBuf;
      const east = bounds.getEast() + lngBuf;

      for (const { marker: mk, venue: v } of markerVenuesRef.current) {
        const ll = mk.getLatLng();
        const inside = ll.lat >= south && ll.lat <= north && ll.lng >= west && ll.lng <= east;
        const onMap = !!((mk as any)._map);
        if (inside && !onMap) {
          mk.addTo(m);
          // Newly-attached marker: paint its current (hour, filter, weather) state.
          applyMarkerVisualState(
            mk,
            computeMarkerState(v, dateKey, hourRef.current, filterRef.current, weatherRef.current),
          );
        } else if (!inside && onMap) {
          mk.remove();
        }
      }
    }

    cullToViewport();
    resolveBadgeCollisions(map, markersRef.current);

    function handleViewportChange() {
      cullToViewport();
      if (mapRef.current) resolveBadgeCollisions(mapRef.current, markersRef.current);
    }
    map.on("zoomend moveend", handleViewportChange);

    return () => {
      map.off("zoomend moveend", handleViewportChange);
    };
  }, [dateKey, typeFilter, sunRange, weather, metroStation]);

  // Hour & sun/shade-filter update — fast path. Retoggles `.marker-dot`'s
  // class and visibility on existing markers. Markers outside the viewport
  // (no `_icon`) are skipped automatically by applyMarkerVisualState.
  useEffect(() => {
    if (!mapRef.current) return;

    for (const { marker, venue } of markerVenuesRef.current) {
      applyMarkerVisualState(
        marker,
        computeMarkerState(venue, dateKey, hour, filter, weatherRef.current),
      );
    }

    // When the sun/shade filter is active, visibility flips per hour. At
    // badge-zoom that means we should re-pack the badges.
    if (filter !== "all" && mapRef.current.getZoom() >= 17) {
      resolveBadgeCollisions(mapRef.current, markersRef.current);
    }
  }, [hour, dateKey, filter]);

  // Pan to selected metro station — own effect so a station change actually
  // pans (the previous version was bundled into the rebuild-on-hour effect).
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !metroStation) return;
    if (focusVenueId) return; // venue focus takes priority — handled below
    map.setView([metroStation.lat, metroStation.lng], 15, { animate: true });
    // Read focusVenueId via closure on mount of this effect; we deliberately
    // omit it from deps so a focus-clear doesn't re-pan to the station.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [metroStation]);

  // Focus on a specific venue (share URL or search). Pans + opens popup once
  // per focusVenueId change, then signals the parent to clear the request.
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !focusVenueId) return;
    const targetVenue = allVenues.find((v: any) => v.id === focusVenueId);
    if (targetVenue) {
      map.setView([targetVenue.lat, targetVenue.lng], 16, { animate: true });
      const found = markerVenuesRef.current.find(({ marker: m }) => {
        const ll = m.getLatLng();
        return Math.abs(ll.lat - targetVenue.lat) < 0.0001 && Math.abs(ll.lng - targetVenue.lng) < 0.0001;
      });
      if (found) {
        // Cull may not have added this marker yet (setView is mid-animation).
        // Force-attach it so openPopup has DOM to render into.
        if (!((found.marker as any)._map)) {
          found.marker.addTo(map);
          applyMarkerVisualState(
            found.marker,
            computeMarkerState(found.venue, dateKey, hourRef.current, filterRef.current, weatherRef.current),
          );
        }
        setTimeout(() => found.marker.openPopup(), 500);
      }
    }
    onFocusHandled?.();
  }, [focusVenueId]);

  // Unconfirmed venues — lazy loaded only at zoom >= 17 and in viewport
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !unconfirmedModule?.unconfirmedVenues) return;

    function renderUnconfirmed() {
      if (!mapRef.current) return;
      const m = mapRef.current;

      // Clear previous unconfirmed markers
      unconfirmedMarkersRef.current.forEach((mk) => mk.remove());
      unconfirmedMarkersRef.current = [];

      if (m.getZoom() < 17) return;

      const bounds = m.getBounds();
      const latBuf = (bounds.getNorth() - bounds.getSouth()) * 0.15;
      const lngBuf = (bounds.getEast() - bounds.getWest()) * 0.15;
      const viewBounds = L.latLngBounds(
        [bounds.getSouth() - latBuf, bounds.getWest() - lngBuf],
        [bounds.getNorth() + latBuf, bounds.getEast() + lngBuf],
      );

      for (const venue of unconfirmedModule!.unconfirmedVenues) {
        if (!viewBounds.contains([venue.lat, venue.lng])) continue;
        if (metroStation) {
          const dist = distanceM(venue.lat, venue.lng, metroStation.lat, metroStation.lng);
          if (dist > STATION_RADIUS_M) continue;
        }
        if (!matchesTypeFilter(venue, typeFilter)) continue;

        const icon = L.divIcon({
          className: "marker-root marker-unconfirmed",
          html: `<div class="marker-dot marker-grey"></div>`,
          iconSize: [10, 10],
          iconAnchor: [5, 5],
          popupAnchor: [0, -9],
        });

        const address = venue.address
          ? `<div style="color:#94a3b8;font-size:11px;margin-top:1px">${venue.address}</div>`
          : "";

        const noticeBg = venue.source === "google_denied" ? "#fef2f2" : "#fffbeb";
        const noticeBorder = venue.source === "google_denied" ? "#fecaca" : "#fde68a";
        const noticeColor = venue.source === "google_denied" ? "#991b1b" : "#92400e";
        const noticeText = venue.source === "google_denied"
          ? "Enligt Google: <b>ingen uteservering</b>"
          : "Ingen bekr&auml;ftad uteservering";

        const mapsUrl = `https://www.google.com/maps/place/${encodeURIComponent(venue.name)}/@${venue.lat},${venue.lng},17z`;
        const mapsPinSvg = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z" fill="#EA4335"/><circle cx="12" cy="9" r="2.5" fill="#fff"/></svg>`;

        const popup = L.popup({ maxWidth: 280 }).setContent(`
          <div style="min-width:220px">
            <div style="margin-bottom:4px">
              <strong style="font-size:14px;line-height:1.2">${venue.name}</strong>
              <div style="color:#64748b;font-size:11px;margin-top:1px">${typeToLabel(venue.type)}</div>
              ${address}
            </div>
            <div id="venue-photo-${venue.id}" style="margin-top:6px"></div>
            <div id="venue-hours-${venue.id}" style="margin-top:4px"></div>
            <div style="background:${noticeBg};border:1px solid ${noticeBorder};border-radius:7px;padding:6px 9px;margin-top:8px;font-size:11px;color:${noticeColor}">
              ${noticeText}
            </div>
            <div style="display:flex;gap:4px;margin-top:8px">
              <a href="${mapsUrl}" target="_blank" rel="noopener noreferrer" title="Öppna i Google Maps"
                style="flex:0 0 32px;padding:3px;border:1px solid #fca5a5;border-radius:6px;background:#fff;display:flex;align-items:center;justify-content:center;text-decoration:none">
                ${mapsPinSvg}
              </a>
              <button class="seating-btn" data-venue-id="${venue.id}"
                style="flex:1;padding:3px 8px;border:1px solid #d1fae5;border-radius:6px;background:#ecfdf5;color:#065f46;font-size:10px;cursor:pointer;text-align:center;font-weight:500">
                Vet du?
              </button>
            </div>
          </div>
        `);

        const marker = L.marker([venue.lat, venue.lng], { icon, zIndexOffset: -200 })
          .addTo(m)
          .bindPopup(popup);

        marker.on("popupopen", () => {
          const photoContainer = document.getElementById(`venue-photo-${venue.id}`);
          if (photoContainer) renderVenuePhoto(photoContainer, venue);

          const hoursContainer = document.getElementById(`venue-hours-${venue.id}`);
          if (hoursContainer) renderVenueHours(hoursContainer, venue);

          // "Vet du?" button → open feedback modal in seating mode
          const seatingBtn = document.querySelector(`.seating-btn[data-venue-id="${venue.id}"]`);
          if (seatingBtn && onFeedback) {
            (seatingBtn as HTMLElement).onclick = () => {
              onFeedback({ id: venue.id, name: venue.name, type: venue.type, currentSchedule: {}, mode: "seating" });
              m.closePopup();
            };
          }
        });

        unconfirmedMarkersRef.current.push(marker);
      }
    }

    map.on("update-unconfirmed", renderUnconfirmed);
    renderUnconfirmed();

    return () => {
      map.off("update-unconfirmed", renderUnconfirmed);
      unconfirmedMarkersRef.current.forEach((mk) => mk.remove());
      unconfirmedMarkersRef.current = [];
    };
  }, [metroStation, typeFilter]);

  // Shadow overlay layer
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    // Remove previous shadow layer
    if (shadowLayerRef.current) {
      shadowLayerRef.current.remove();
      shadowLayerRef.current = null;
    }

    if (!showShadows) return;

    const key = `${dateKey}_${String(hour).padStart(2, "0")}`;
    const url = `/api/shadows?key=${key}`;

    const cached = shadowCache.get(key);
    if (cached) {
      shadowLayerRef.current = L.geoJSON(cached, {
        style: { color: "transparent", fillColor: "#1e293b", fillOpacity: 0.18, stroke: false },
        interactive: false,
      }).addTo(map);
      return;
    }

    fetch(url)
      .then((res) => {
        if (!res.ok) return null;
        return res.json();
      })
      .then((data) => {
        if (!data || !mapRef.current) return;
        shadowCache.set(key, data);
        // Only add if still the current timepoint
        if (shadowLayerRef.current) shadowLayerRef.current.remove();
        shadowLayerRef.current = L.geoJSON(data, {
          style: { color: "transparent", fillColor: "#1e293b", fillOpacity: 0.18, stroke: false },
          interactive: false,
        }).addTo(mapRef.current);
      })
      .catch(() => {});
  }, [hour, dateKey, showShadows]);

  // Geolocation — watch position and show blue dot on map
  function handleLocate() {
    if (!navigator.geolocation) { setGeoState("error"); return; }
    if (geoState === "located") {
      // Second click: stop watching and remove marker
      if (geoWatchRef.current !== null) {
        navigator.geolocation.clearWatch(geoWatchRef.current);
        geoWatchRef.current = null;
      }
      userMarkerRef.current?.remove();
      userMarkerRef.current = null;
      hasCenteredRef.current = false;
      setGeoState("idle");
      return;
    }
    setGeoState("locating");
    hasCenteredRef.current = false;
    if (geoWatchRef.current !== null) navigator.geolocation.clearWatch(geoWatchRef.current);
    geoWatchRef.current = navigator.geolocation.watchPosition(
      (pos) => {
        const { latitude, longitude } = pos.coords;
        const map = mapRef.current;
        if (!map) return;
        setGeoState("located");
        if (!userMarkerRef.current) {
          const icon = L.divIcon({
            className: "",
            html: `<div class="user-location-dot"></div>`,
            iconSize: [18, 18],
            iconAnchor: [9, 9],
          });
          userMarkerRef.current = L.marker([latitude, longitude], { icon, zIndexOffset: 2000, interactive: false }).addTo(map);
        } else {
          userMarkerRef.current.setLatLng([latitude, longitude]);
        }
        if (!hasCenteredRef.current) {
          map.setView([latitude, longitude], 16, { animate: true });
          hasCenteredRef.current = true;
        }
      },
      () => setGeoState("error"),
      { enableHighAccuracy: true, timeout: 10000 },
    );
  }

  // Cleanup geolocation watch on unmount
  useEffect(() => {
    return () => {
      if (geoWatchRef.current !== null) navigator.geolocation.clearWatch(geoWatchRef.current);
    };
  }, []);

  const currentWeatherSymbol = weather?.hourly[hour]?.symbolCode;
  const darkness = getAmbientDarkness(hour, date, currentWeatherSymbol);
  const ambientColor = getAmbientColor(hour, date, currentWeatherSymbol);

  // Darken the map via CSS filter on Leaflet's tile + overlay panes — this is
  // the only reliable way to avoid affecting popups, because leaflet-map-pane
  // has a CSS transform and forms its own stacking context (anything layered
  // outside it ends up above every pane, including the popup pane).
  //
  // Markers get their own dampening via a CSS variable on the `.marker-dot`
  // child element, leaving the sibling `.marker-badge` untouched.
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const tilePane = container.querySelector<HTMLElement>(".leaflet-tile-pane");
    const overlayPane = container.querySelector<HTMLElement>(".leaflet-overlay-pane");
    if (!tilePane || !overlayPane) return;

    const brightness = Math.max(0.35, 1 - darkness * 0.9);
    const [r, , b] = ambientColor.split(",").map((n) => Number(n.trim()));
    const warmBias = (r - b) / 255;
    const hueRotate = -warmBias * 12 * darkness;
    const saturate = 1 - darkness * 0.25;

    const tileFilter = `brightness(${brightness}) saturate(${saturate}) hue-rotate(${hueRotate}deg)`;
    tilePane.style.filter = tileFilter;
    tilePane.style.transition = "filter 0.8s ease";
    overlayPane.style.filter = tileFilter;
    overlayPane.style.transition = "filter 0.8s ease";

    const markerBrightness = Math.max(0.55, 1 - darkness * 0.55);
    const markerSaturate = 1 - darkness * 0.2;
    container.style.setProperty("--marker-dot-filter", `brightness(${markerBrightness}) saturate(${markerSaturate})`);
  }, [darkness, ambientColor]);

  const [showTooltip, setShowTooltip] = useState(true);
  useEffect(() => {
    const t = setTimeout(() => setShowTooltip(false), 4500);
    return () => clearTimeout(t);
  }, []);

  const locateBtnColor = geoState === "located" ? "#3b82f6" : geoState === "error" ? "#ef4444" : "#1e293b";
  const glassStyle: React.CSSProperties = {
    background: "rgba(255, 255, 255, 0.3)",
    backdropFilter: "blur(14px) saturate(1.3)",
    WebkitBackdropFilter: "blur(14px) saturate(1.3)",
    border: "0.5px solid rgba(255, 255, 255, 0.55)",
    boxShadow: "0 4px 16px rgba(0,0,0,0.12)",
  };

  // Search — outside click + Escape close
  useEffect(() => {
    if (!searchOpen) return;
    const onClick = (e: MouseEvent) => {
      if (searchRef.current && !searchRef.current.contains(e.target as Node)) {
        setSearchOpen(false);
        setSearchQuery("");
      }
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") { setSearchOpen(false); setSearchQuery(""); }
    };
    document.addEventListener("mousedown", onClick);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onClick);
      document.removeEventListener("keydown", onKey);
    };
  }, [searchOpen]);

  const searchResults = useMemo(() => {
    const q = searchQuery.trim().toLowerCase();
    if (!q) return [] as any[];
    const out: any[] = [];
    for (const v of allVenues) {
      if ((v.name || "").toLowerCase().includes(q)) {
        out.push(v);
        if (out.length >= 8) break;
      }
    }
    return out;
  }, [searchQuery]);

  function flyToSearchResult(venue: any) {
    const map = mapRef.current;
    if (!map) return;
    map.setView([venue.lat, venue.lng], 17, { animate: true });
    const found = markerVenuesRef.current.find(({ marker: m }) => {
      const ll = m.getLatLng();
      return Math.abs(ll.lat - venue.lat) < 0.0001 && Math.abs(ll.lng - venue.lng) < 0.0001;
    });
    if (found) {
      if (!((found.marker as any)._map)) {
        found.marker.addTo(map);
        applyMarkerVisualState(
          found.marker,
          computeMarkerState(found.venue, dateKey, hourRef.current, filterRef.current, weatherRef.current),
        );
      }
      setTimeout(() => found.marker.openPopup(), 500);
    }
    setSearchOpen(false);
    setSearchQuery("");
  }

  return (
    <div className="w-full h-full relative">
      <div ref={containerRef} className="w-full h-full" />

      {/* Search button — stacked above GPS, slides out an input + dropdown when open */}
      <div
        ref={searchRef}
        style={{ position: "absolute", bottom: "281px", right: "12px", zIndex: 1001, display: "flex", alignItems: "center", gap: 8 }}
      >
        {searchOpen && (
          <div style={{ position: "relative" }}>
            {searchResults.length > 0 && (
              <div
                style={{
                  ...glassStyle,
                  position: "absolute",
                  right: 0,
                  bottom: "calc(100% + 8px)",
                  width: 280,
                  maxHeight: 320,
                  overflowY: "auto",
                  borderRadius: 14,
                  padding: 4,
                  fontFamily: "var(--font-outfit), var(--font-inter), system-ui, sans-serif",
                }}
              >
                {searchResults.map((v: any) => (
                  <button
                    key={v.id}
                    onClick={() => flyToSearchResult(v)}
                    style={{
                      display: "block",
                      width: "100%",
                      padding: "8px 10px",
                      background: "transparent",
                      border: "none",
                      borderRadius: 10,
                      textAlign: "left",
                      cursor: "pointer",
                      color: "#0f172a",
                      transition: "background 0.12s ease",
                    }}
                    onMouseEnter={(e) => (e.currentTarget.style.background = "rgba(255,255,255,0.5)")}
                    onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
                  >
                    <div style={{ fontSize: 13, fontWeight: 600, lineHeight: 1.25 }}>{v.name}</div>
                    {v.address && (
                      <div style={{ fontSize: 11, color: "#64748b", marginTop: 2, lineHeight: 1.2, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        {v.address}
                      </div>
                    )}
                  </button>
                ))}
              </div>
            )}
            {searchQuery.trim() && searchResults.length === 0 && (
              <div
                style={{
                  ...glassStyle,
                  position: "absolute",
                  right: 0,
                  bottom: "calc(100% + 8px)",
                  width: 280,
                  borderRadius: 14,
                  padding: "10px 12px",
                  fontSize: 12,
                  color: "#64748b",
                  fontFamily: "var(--font-outfit), var(--font-inter), system-ui, sans-serif",
                }}
              >
                Inga ställen matchar &ldquo;{searchQuery}&rdquo;
              </div>
            )}
            <input
              autoFocus
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Sök ställe..."
              style={{
                ...glassStyle,
                height: 48,
                width: 240,
                padding: "0 16px",
                borderRadius: 14,
                fontSize: 14,
                color: "#0f172a",
                outline: "none",
                fontFamily: "var(--font-outfit), var(--font-inter), system-ui, sans-serif",
              }}
            />
          </div>
        )}

        <button
          onClick={() => {
            if (searchOpen) { setSearchOpen(false); setSearchQuery(""); }
            else setSearchOpen(true);
          }}
          title={searchOpen ? "Stäng sök" : "Sök ställe"}
          style={{
            ...glassStyle,
            width: 48,
            height: 48,
            borderRadius: 14,
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "#1e293b",
            flexShrink: 0,
          }}
        >
          {searchOpen ? (
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          ) : (
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="11" cy="11" r="7" />
              <line x1="21" y1="21" x2="16.65" y2="16.65" />
            </svg>
          )}
        </button>
      </div>

      {/* GPS locate button — bottom-right above time slider */}
      <div style={{ position: "absolute", bottom: "225px", right: "12px", zIndex: 1001, display: "flex", alignItems: "center", gap: 8 }}>
        {/* Tooltip — fades in then out, only when idle */}
        {showTooltip && geoState === "idle" && (
          <div style={{
            ...glassStyle,
            borderRadius: 12,
            padding: "7px 12px",
            fontSize: 12,
            fontWeight: 500,
            color: "#0f172a",
            whiteSpace: "nowrap",
            animation: "gps-tip 4.5s ease forwards",
            fontFamily: "var(--font-outfit), var(--font-inter), system-ui, sans-serif",
          }}>
            Aktivera GPS för att se din position
          </div>
        )}

        <button
          onClick={() => { setShowTooltip(false); handleLocate(); }}
          title={geoState === "located" ? "Dölj min position" : "Visa min position"}
          style={{
            ...glassStyle,
            width: 48,
            height: 48,
            borderRadius: 14,
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: locateBtnColor,
            flexShrink: 0,
          }}
        >
          {geoState === "locating" ? (
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ animation: "spin 1s linear infinite" }}>
              <circle cx="12" cy="12" r="10" strokeOpacity="0.3" />
              <path d="M12 2a10 10 0 0 1 10 10" />
            </svg>
          ) : (
            <svg width="22" height="22" viewBox="0 0 24 24" fill={geoState === "located" ? "currentColor" : "none"} stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="3" />
              <path d="M12 2v3M12 19v3M2 12h3M19 12h3" />
              <circle cx="12" cy="12" r="8" />
            </svg>
          )}
        </button>
      </div>

      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        @keyframes gps-tip {
          0%   { opacity: 0; transform: translateX(6px); }
          12%  { opacity: 1; transform: translateX(0); }
          75%  { opacity: 1; }
          100% { opacity: 0; }
        }
      `}</style>
    </div>
  );
}
